[versions]
kotlin = "[2.3,3.0)"
ktlint = "[14.0,15.0)"
shadow = "[9.3,10.0)"
jreleaser = "[1.21,2.0)"
zmknLog = "1.0.0-SNAPSHOT"
nacos = "[3.1,4.0)"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

[libraries]
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }

zmkn-log-logger-kotlin = { group = "com.zmkn.log", name = "logger-kotlin", version.ref = "zmknLog" }
nacos-client = { group = "com.alibaba.nacos", name = "nacos-client", version.ref = "nacos" }
